### PR TITLE
fix(collector): fix documentation for `ResourceMetricCollector.clear()` function

### PR DESCRIPTION
**Pull request by MyGodItsFull0fStars**
The docstrings of `ResourceMetricCollector` referred to the `clear()` function as `reset()`, which is not existing. 
Therefore, I replaced each mention of `reset()` with `clear()` in the documentation.

#### Issue Type

- Improvement/feature implementation

#### Runtime Environment

- Operating system and version: [e.g. Ubuntu 20.04 LTS / Windows 10 Build 19043.1110]
- Terminal emulator and version: [e.g. GNOME Terminal 3.36.2 / Windows Terminal 1.8.1521.0]
- Python version: [e.g. `3.7.2` / `3.9.6`]
- NVML version (driver version): [e.g. `460.84`]
- `nvitop` version or commit: [e.g. `0.10.0` / `0.10.1.dev7+ga083321` / `main@75ae3c`]
- `python-ml-py` version: [e.g. `11.450.51`]
- Locale: [e.g. `C` / `C.UTF-8` / `en_US.UTF-8`]

#### Description

Within the `ResourceMetricCollector` class, the `clear()` function was not used in the documentation for the class, nor the docstring of the function itself, but `reset()`.

As the `reset()` function is not existing for `ResourceMetricCollector`, I replaced all occurrences of it in the documentation with `clear()` as well as changing the description of the `clear()` function to reflect it's name better.

#### Motivation and Context

The motivation is, that I was looking at the documentation and tried to use the `reset()` function for a `ResourceMetricCollector` instance, and encountered an error.
I had to look at the code to see that the function I have to use is called `clear()`.

#### Testing

As I only changed the docstrings within the `ResourceMetricCollector` class, I did not test my changes.

### CODE REVIEW

**Comment by XuehaiPan** [comment]
Hi @MyGodItsFull0fStars, thanks for raising this. Would you mind also add an alias above the method to make both name work?

```python
class ResourceMetricCollector:
    ...

    def clear(self, tag: str | None = None) -> None:
        ...

    reset = clear

    ...
```

**Comment by MyGodItsFull0fStars** [comment]
Hi @XuehaiPan, thank you for the quick reply.

Sure, will gladly do so.
I will push your suggestions once I tested both variants.

**Comment by MyGodItsFull0fStars** [comment]
@XuehaiPan I just pushed the commit that includes the `reset` alias for the `clear` function in `ResourceMetricCollector`.

**Comment by MyGodItsFull0fStars** [comment]
Hey @XuehaiPan, here is a friendly reminder that I have added the requested alias for `reset` and the code should now be fine.

**Review by XuehaiPan — APPROVED** [review]

**Pull request merged**
